# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "94d8d579b7b2a4f4fa7d9a7400386b22"
name = "my-app"
application_url = "https://shopify-assignment.onrender.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://shopify-assignment.onrender.com/api/auth/callback" ]

[webhooks]
api_version = "2026-07"

[build]
automatically_update_urls_on_dev = true
